# Generated by Django 4.1 on 2023-11-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('num_of_points', models.IntegerField()),
                ('base_color', models.IntegerField()),
                ('hover_color', models.IntegerField()),
                ('feedback_1', models.IntegerField()),
                ('feedback_2', models.IntegerField()),
                ('feedback_3', models.IntegerField()),
                ('feedback_4', models.IntegerField()),
            ],
        ),
    ]
