# Generated by Django 4.1 on 2023-12-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Road', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='name',
            field=models.CharField(default='Road', max_length=20, unique=True),
        ),
    ]
