# Generated by Django 4.1 on 2023-11-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Road', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='point_1s',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='road',
            name='point_2e',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='road',
            name='point_2s',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='road',
            name='point_3e',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='road',
            name='point_3s',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='road',
            name='point_4e',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='road',
            name='point_4s',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
    ]
