# Generated by Django 4.1 on 2023-11-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Road', '0003_road_point_1e'),
    ]

    operations = [
        migrations.RenameField(
            model_name='road',
            old_name='point_1e',
            new_name='point_1x',
        ),
        migrations.RenameField(
            model_name='road',
            old_name='point_1s',
            new_name='point_1y',
        ),
        migrations.RenameField(
            model_name='road',
            old_name='point_2e',
            new_name='point_2x',
        ),
        migrations.RenameField(
            model_name='road',
            old_name='point_2s',
            new_name='point_2y',
        ),
        migrations.RenameField(
            model_name='road',
            old_name='point_3e',
            new_name='point_3x',
        ),
        migrations.RenameField(
            model_name='road',
            old_name='point_3s',
            new_name='point_3y',
        ),
        migrations.RenameField(
            model_name='road',
            old_name='point_4e',
            new_name='point_4x',
        ),
        migrations.RenameField(
            model_name='road',
            old_name='point_4s',
            new_name='point_4y',
        ),
    ]
