# Generated by Django 4.1 on 2023-11-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Road', '0004_rename_point_1e_road_point_1x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='point_1x',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='road',
            name='point_1y',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='road',
            name='point_2x',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='road',
            name='point_2y',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='road',
            name='point_3x',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='road',
            name='point_3y',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='road',
            name='point_4x',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='road',
            name='point_4y',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
        ),
    ]
