# Generated by Django 4.2.7 on 2023-11-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30, verbose_name="用户名")),
                ("password", models.CharField(max_length=30, verbose_name="密码")),
                ("email", models.EmailField(max_length=254, verbose_name="邮箱")),
                ("role", models.IntegerField(default=0, verbose_name="角色")),
                ("isDelete", models.IntegerField(default=0, verbose_name="是否删除")),
            ],
            options={
                "verbose_name": "用户表",
                "verbose_name_plural": "用户表",
                "db_table": "user",
            },
        ),
    ]
