# Generated by Django 4.2.7 on 2023-11-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="email",),
        migrations.RemoveField(model_name="user", name="isDelete",),
        migrations.RemoveField(model_name="user", name="role",),
    ]
