# Generated by Django 4.1 on 2023-12-13 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=-1)),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('opening_hours', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('x', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('y', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='TagTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.location')),
            ],
        ),
        migrations.CreateModel(
            name='TagPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.location')),
            ],
        ),
        migrations.CreateModel(
            name='TagFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.location')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000)),
                ('username', models.CharField(max_length=10000)),
                ('timestamp', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.location')),
            ],
        ),
    ]
