# Generated by Django 4.1 on 2023-12-14 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagfunction',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tagplace',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tagtime',
            name='location',
        ),
        migrations.CreateModel(
            name='Location_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.location')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.tagtime')),
            ],
        ),
        migrations.CreateModel(
            name='Location_Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.location')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.tagplace')),
            ],
        ),
        migrations.CreateModel(
            name='Location_Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.location')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.tagfunction')),
            ],
        ),
    ]
