# Generated by Django 4.2.7 on 2023-11-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppUser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="password",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="username",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
