# Generated by Django 4.2.7 on 2023-11-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppUser", "0002_appuser_email_alter_appuser_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
