# Generated by Django 4.2.7 on 2023-11-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppUser", "0003_alter_appuser_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerifyCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="appuser",
            name="is_activity",
            field=models.BooleanField(default=False),
        ),
    ]
