# Generated by Django 4.1 on 2023-11-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0004_verifycode_appuser_is_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='code',
            field=models.CharField(max_length=8),
        ),
    ]
